# Generated by Django 5.1.6 on 2025-04-14 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='caracteristica')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='ordem')),
                ('caracteristica', models.ManyToManyField(blank=True, related_name='caracteristica', to='app.caracteristica')),
            ],
            options={
                'verbose_name': 'Ordem',
                'verbose_name_plural': 'Ordens',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='especie')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='app.ordem')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
    ]
