# Generated by Django 5.1.6 on 2025-09-24 12:44

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='caracteristica')),
            ],
            options={
                'verbose_name': 'Característica',
                'verbose_name_plural': 'Características',
            },
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo da Referência')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='ordem')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo da descrição')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo da descrição em inglês')),
                ('caracteristica', models.ManyToManyField(blank=True, related_name='caracteristica', to='entomologia.caracteristica')),
            ],
            options={
                'verbose_name': 'Ordem',
                'verbose_name_plural': 'Ordens',
            },
        ),
        migrations.CreateModel(
            name='ImagemOrdem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='ordem_galeria')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='entomologia.ordem')),
            ],
            options={
                'verbose_name': 'Galeria da Ordem',
                'verbose_name_plural': 'Galeria das Ordens',
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('imagem', models.ImageField(upload_to='especie')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='entomologia.ordem')),
            ],
            options={
                'verbose_name': 'Especie',
                'verbose_name_plural': 'Especies',
            },
        ),
    ]
