# Generated by Django 5.1.6 on 2025-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entomologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='familia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
