# Generated by Django 5.1.6 on 2025-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entomologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
