# Generated by Django 5.1.6 on 2025-05-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entomologia', '0002_sitecounter_ordem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='SiteCounter',
        ),
    ]
