# Generated by Django 5.1.6 on 2025-09-24 13:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entomologia', '0002_especie_familia_especie_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título em Português')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title in English')),
                ('corpo', ckeditor.fields.RichTextField(verbose_name='Corpo da notícia em Português')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body of the news in English')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias', verbose_name='Imagem (Opcional)')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
