# Generated by Django 5.1.6 on 2025-05-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entomologia', '0002_ordem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contador de Visitas',
                'verbose_name_plural': 'Contadores de Visitas',
            },
        ),
    ]
