# Generated by Django 5.1.6 on 2025-05-08 01:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entomologia', '0003_visitorcount_delete_sitecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo da Referência')),
            ],
            options={
                'verbose_name': 'Referência',
                'verbose_name_plural': 'Referências',
            },
        ),
        migrations.AlterField(
            model_name='ordem',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo da descrição'),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Conteúdo da descrição em inglês'),
        ),
    ]
